steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=go_server"]
    args: ["build", "-o", "server.go", "./simple_api.go"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["compute", "scp", "--zone=us-west2-a", "server.go", "unity-test:~/"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "ssh",
        "--zone=us-west2-a",
        "unity-test",
        "--command",
        "chmod +x ~/server.go",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "ssh",
        "--zone=us-west2-a",
        "unity-test",
        "--command",
        "nohup ~/server.go &",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
