steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=go_server"]
    args: ["build", "-o", "server", "go_server/simple_api.go"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "scp",
        "--zone=us-west2-a",
        "go_server/server",
        "unity-test:~/",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "ssh",
        "--zone=us-west2-a",
        "unity-test",
        "--command",
        "chmod +x ~/server",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "ssh",
        "--zone=us-west2-a",
        "unity-test",
        "--command",
        "nohup ~/server &",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
